# Generated by Django 2.2.9 on 2020-03-09 09:10

import common.consts
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problemset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('visible', models.BooleanField(db_index=True, default=False)),
                ('category', models.SmallIntegerField(choices=[(0, 'OPEN'), (1, 'PRIVATE'), (2, 'REGISTER'), (3, 'SOLO')], default=common.consts.ContestCategory(0))),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalties', django_mysql.models.JSONField(blank=True, default=dict, help_text='problem_id:penalty mapping, if penalty is negative, it represents the number of wrong submissions')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_order', models.PositiveSmallIntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemset.Problem')),
            ],
            options={
                'ordering': ('problem_order',),
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(blank=True, through='contest.ContestProblem', to='problemset.Problem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='standing',
            constraint=models.UniqueConstraint(fields=('contest', 'user'), name='unique_contest_user'),
        ),
    ]
