# Generated by Django 2.2.9 on 2020-02-16 11:57

import common.consts
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0003_auto_20200208_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'OPEN'), (1, 'PRIVATE'), (2, 'REGISTER')], default=common.consts.ContestCategory(0)),
        ),
        migrations.AddField(
            model_name='contest',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalties', django_mysql.models.JSONField(blank=True, default=dict, help_text='problem_id:penalty mapping, if penalty is negative, it represents the number of wrong submissions')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='standing',
            constraint=models.UniqueConstraint(fields=('contest', 'user'), name='unique_contest_user'),
        ),
    ]
