# Generated by Django 2.2.9 on 2020-02-22 08:02

import common.consts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20200216_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'OPEN'), (1, 'PRIVATE'), (2, 'REGISTER'), (3, 'SOLO')], default=common.consts.ContestCategory(0)),
        ),
    ]
