# Generated by Django 2.2.9 on 2020-03-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20200222_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='visible',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
