# Generated by Django 2.2.9 on 2020-03-09 09:10

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField(default=2000, help_text='In ms')),
                ('memory_limit', models.IntegerField(default=131072, help_text='In KB')),
                ('note', django_mysql.models.JSONField(blank=True, default=list)),
                ('sample_inputs', django_mysql.models.JSONField(default=list)),
                ('sample_outputs', django_mysql.models.JSONField(default=list)),
                ('checker_type', models.SmallIntegerField(choices=[(0, 'same'), (1, 'acmp'), (2, 'caseicmp'), (3, 'casencmp'), (4, 'casewcmp'), (5, 'dcmp'), (6, 'fcmp'), (7, 'hcmp'), (8, 'icmp'), (9, 'lcmp'), (10, 'ncmp'), (11, 'nyesno'), (12, 'pointscmp'), (13, 'rcmp'), (14, 'rcmp4'), (15, 'rcmp6'), (16, 'rcmp9'), (17, 'rncmp'), (18, 'uncmp'), (19, 'wcmp'), (20, 'yesno'), (100, 'special_judge')])),
                ('checker_code', models.TextField(blank=True)),
                ('visible', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', django_mysql.models.JSONField(default=list)),
                ('expected_outputs', django_mysql.models.JSONField(default=list)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problemset.Problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('lang', models.SmallIntegerField(choices=[(1, 'GXX'), (2, 'GCC'), (3, 'JAVA'), (4, 'CPY'), (5, 'PYPY'), (6, 'GO'), (7, 'JS')])),
                ('is_model_solution', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problemset.Problem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.UniqueConstraint(fields=('problem', 'is_model_solution'), name='unique_problem_model_solution'),
        ),
    ]
