# Generated by Django 2.1.14 on 2019-12-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sample_inputs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_outputs',
            field=models.TextField(blank=True),
        ),
    ]
