# Generated by Django 2.1.14 on 2019-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0002_auto_20191202_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_model_solution',
            field=models.BooleanField(default=False),
        ),
    ]
