# Generated by Django 2.2.9 on 2020-04-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0003_auto_20200407_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='lang',
            field=models.SmallIntegerField(choices=[(1, 'GXX'), (2, 'GCC'), (3, 'JAVA'), (4, 'CPY'), (5, 'PYPY'), (6, 'RACKET')]),
        ),
    ]
