# Generated by Django 2.1.14 on 2019-12-07 10:00

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0003_solution_is_model_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='sample_inputs',
            field=django_mysql.models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_outputs',
            field=django_mysql.models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_outputs',
            field=django_mysql.models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='inputs',
            field=django_mysql.models.JSONField(default=list),
        ),
    ]
