# Generated by Django 2.2.9 on 2020-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0004_auto_20200420_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
