# Generated by Django 2.1.14 on 2019-12-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0004_auto_20191207_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='checker_type',
            field=models.SmallIntegerField(choices=[(0, 'same'), (1, 'acmp'), (2, 'caseicmp'), (3, 'casencmp'), (4, 'casewcmp'), (5, 'dcmp'), (6, 'fcmp'), (7, 'hcmp'), (8, 'icmp'), (9, 'lcmp'), (10, 'ncmp'), (11, 'nyesno'), (12, 'pointscmp'), (13, 'rcmp'), (14, 'rcmp4'), (15, 'rcmp6'), (16, 'rcmp9'), (17, 'rncmp'), (18, 'uncmp'), (19, 'wcmp'), (20, 'yesno'), (100, 'special_judge')]),
        ),
    ]
