# Generated by Django 2.2.24 on 2021-10-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0005_auto_20200427_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
