# Generated by Django 2.1.14 on 2020-01-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0006_auto_20191225_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='checker_code',
            field=models.TextField(blank=True),
        ),
    ]
