# Generated by Django 2.2.24 on 2021-11-11 05:17

import common.consts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0006_delete_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='verdict',
            field=models.SmallIntegerField(choices=[(-1, 'PENDING'), (0, 'AC'), (1, 'PE'), (2, 'TLE'), (3, 'MLE'), (4, 'WA'), (5, 'RE'), (6, 'OLE'), (7, 'CE'), (8, 'SE')], default=common.consts.VerdictResult(0)),
        ),
    ]
