# Generated by Django 2.1.14 on 2020-01-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0007_problem_checker_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
