# Generated by Django 2.2.9 on 2020-01-31 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0008_problem_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='lang',
            field=models.SmallIntegerField(choices=[(1, 'GXX'), (2, 'GCC'), (3, 'Java'), (4, 'CPY'), (5, 'PYPY'), (6, 'Go'), (7, 'JavaScript')]),
        ),
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problemset.Problem'),
        ),
    ]
