# Generated by Django 2.2.9 on 2020-02-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0009_auto_20200131_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='lang',
            field=models.SmallIntegerField(choices=[(1, 'GXX'), (2, 'GCC'), (3, 'JAVA'), (4, 'CPY'), (5, 'PYPY'), (6, 'GO'), (7, 'JS')]),
        ),
    ]
