# Generated by Django 2.2.9 on 2020-02-29 14:57

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0010_auto_20200216_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='note',
            field=django_mysql.models.JSONField(blank=True, default=list),
        ),
    ]
