# Generated by Django 2.2.9 on 2020-03-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0011_auto_20200229_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='visible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.UniqueConstraint(fields=('problem', 'is_model_solution'), name='unique_problem_model_solution'),
        ),
    ]
