# Generated by Django 2.2.9 on 2020-03-09 09:10

import common.consts
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problemset', '0001_initial'),
        ('contest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField()),
                ('lang', models.SmallIntegerField(choices=[(1, 'GXX'), (2, 'GCC'), (3, 'JAVA'), (4, 'CPY'), (5, 'PYPY'), (6, 'GO'), (7, 'JS')])),
                ('time', models.IntegerField(default=0, help_text='In ms')),
                ('memory', models.IntegerField(default=0, help_text='In KB')),
                ('verdict', models.SmallIntegerField(choices=[(-1, 'PENDING'), (0, 'AC'), (1, 'PE'), (2, 'TLE'), (3, 'MLE'), (4, 'WA'), (5, 'RE'), (6, 'OLE'), (7, 'CE'), (8, 'SE')], default=common.consts.VerdictResult(-1))),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('outputs', django_mysql.models.JSONField(blank=True, default=list)),
                ('job_id', models.CharField(blank=True, help_text='The job id in RQ', max_length=50, null=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contest.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='problemset.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
