# Generated by Django 2.1 on 2019-11-23 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField()),
                ('code', models.TextField()),
                ('lang', models.SmallIntegerField(choices=[(1, 'CPP'), (2, 'C'), (3, 'Java'), (4, 'Python2'), (5, 'Python3'), (6, 'Go'), (7, 'JavaScript')])),
                ('time', models.IntegerField(help_text='In ms')),
                ('memory', models.IntegerField(help_text='In KB')),
                ('verdict', models.SmallIntegerField(choices=[(0, 'AC'), (1, 'WA'), (2, 'TLE'), (4, 'RE'), (8, 'MLE'), (16, 'OLE'), (32, 'CE'), (1073741824, 'IE')])),
                ('outputs', models.TextField(help_text='a list formatted in JSON')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='problemset.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
