# Generated by Django 2.1.14 on 2019-11-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(help_text='In KB', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='outputs',
            field=models.TextField(help_text='a list formatted in JSON', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.IntegerField(help_text='In ms', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.SmallIntegerField(choices=[(0, 'AC'), (1, 'WA'), (2, 'TLE'), (4, 'RE'), (8, 'MLE'), (16, 'OLE'), (32, 'CE'), (1073741824, 'IE')], null=True),
        ),
    ]
