# Generated by Django 2.1.14 on 2019-11-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191130_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='job_id',
            field=models.CharField(help_text='The job id in RQ', max_length=50, null=True),
        ),
    ]
