# Generated by Django 2.2.9 on 2020-04-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200318_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.SmallIntegerField(choices=[(1, 'GXX'), (2, 'GCC'), (3, 'JAVA'), (4, 'CPY'), (5, 'PYPY'), (6, 'RACKET')]),
        ),
    ]
