# Generated by Django 2.1.14 on 2019-12-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_submission_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='desc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
