# Generated by Django 2.1.14 on 2019-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_submission_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
