# Generated by Django 2.1.14 on 2019-12-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191204_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(default=0, help_text='In KB'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.IntegerField(default=0, help_text='In ms'),
        ),
    ]
