# Generated by Django 2.1.14 on 2019-12-07 10:00

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191207_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='outputs',
            field=django_mysql.models.JSONField(default=list),
        ),
    ]
