# Generated by Django 2.1.14 on 2019-12-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191207_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.SmallIntegerField(choices=[(0, 'AC'), (1, 'PE'), (2, 'TLE'), (3, 'MLE'), (4, 'WA'), (5, 'RE'), (6, 'OLE'), (7, 'CE'), (8, 'SE')], null=True),
        ),
    ]
