# Generated by Django 2.1.14 on 2019-12-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191216_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='job_id',
            field=models.CharField(blank=True, help_text='The job id in RQ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'AC'), (1, 'PE'), (2, 'TLE'), (3, 'MLE'), (4, 'WA'), (5, 'RE'), (6, 'OLE'), (7, 'CE'), (8, 'SE')], null=True),
        ),
    ]
