# Generated by Django 2.2.9 on 2020-01-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20191225_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.SmallIntegerField(choices=[(1, 'GXX'), (2, 'GCC'), (3, 'Java'), (4, 'CPY'), (5, 'PYPY'), (6, 'Go'), (7, 'JavaScript')]),
        ),
    ]
