# Generated by Django 2.2.9 on 2020-02-08 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20200208_1622'),
        ('user', '0011_auto_20200131_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contest.Contest'),
        ),
    ]
