# Generated by Django 2.2.9 on 2020-02-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_submission_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contest.Contest'),
        ),
    ]
